POST http://localhost:4000/admin/login
Content-Type: application/json

{
    "username": "siddhu",
    "password": "1234"
}

###
POST http://localhost:4000/user/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjVmODNhZGNjYzkzMTdhODI0ODFlYWM5IiwiaWF0IjoxNzE0MDM1OTM3LCJleHAiOjE3MTQwNzkxMzd9.Ol6kPswFzWk26iHTEWtoibhUQNx7rh8h0ZaWoRTIat8

{
    "email": "o10@rguktong.ac.in",
    "firstName": "Kumar ",
    "lastName": "Sass",
    "college": "RGUKT ONGOLE",
    "phno": "994410059",
    "year": "E3",
    "branch": "CSE",
    "collegeId": "o10",
    "amountPaid": 199,
    "state": "Andhra Pradesh",
    "district": "Prakasam",
    "city": "Ongole",
    "mode": "offline_mode"
 
}

###
DELETE http://localhost:4000/user/delete/tzk240166




###
POST http://localhost:4000/qr/users
Content-Type: application/json

{
  "tzkid": "123456789",
  "email": "example@example.com",
  "firstName": "John",
  "lastName": "Doe",
  "college": "Example University",
  "phno": 1234567890,
  "year": "Senior",
  "branch": "Computer Science",
  "collegeId": "E12345",
  "amountPaid": 50,
  "gender": "Male",
  "state": "Example State",
  "district": "Example District",
  "city": "Example City",
  "mode": "Online",
  "createdAt": "2024-04-24T12:00:00.000Z",
  "updatedAt": "2024-04-24T12:00:00.000Z",
  "referredBy": "example_referrer",
  "rezorpay_order_id": "R123456",
  "refreals": ["referral1", "referral2"],
  "regEvents": ["event1", "event2"],
  "regWorkshop": ["workshop1", "workshop2"]
}





###
GET http://localhost:4000/user/getAll
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjVmODNhZGNjYzkzMTdhODI0ODFlYWM5IiwiaWF0IjoxNzE0MTI1Njg1LCJleHAiOjE3MTQxNjg4ODV9.NxAmXrfOlxmW4OCv-LWuGB2YgBs3DTT1nZ_Cve729oU





POST https://bill-server-hiq9.onrender.com/